from pathlib import Path
import re
import nbformat
root=Path(__file__).resolve().parents[2]
out=root/'code_sample'
source=(out/'code_sample.py').read_text()
parts=re.split(r'^# %% (.+)\n',source,flags=re.M)
nb=nbformat.v4.new_notebook()
nb.cells=[nbformat.v4.new_markdown_cell('''# County health, social needs, and descriptive risk profiles
**Donghang Zou · Global AI internship · Python code sample**

Which social conditions accompany diabetes and hypertension, and how do counties group by burden? The full project stacks **CDC PLACES releases 2021–2025** with **SVI 2020/2022**. This executable excerpt rebuilds its latest snapshot from raw CSVs: **2025 PLACES** (2023 outcomes; some 2022 measures) and **SVI 2022**.

Run from the repository root or `code_sample/`. Tables and figures below are generated by the code; writes are confined to `code_sample/`.'''),nbformat.v4.new_code_cell(parts[0].strip())]
notes={
 '1. CSV ingestion and county snapshot':'Age adjustment keeps prevalence comparable across county age structures. The one-to-one merge protects the unit of analysis; SVI −999 values are missing, not low vulnerability.',
 '2. One analytical function, two explicit sampling policies':'Each factor has its own pairwise sample. Reusing the function on a common sample reveals how geographic coverage changes the comparison. `n` refers to the pairwise county count; `common_r` and `common_n` refer to diabetes.',
 '3. Visualize the strongest diabetes correlates and their hypertension associations':'The four factors shown are the strongest positive diabetes correlates among all 16 candidate factors; the second column shows their associations with hypertension.',
 '4. Cluster the same 16 features used in the full notebook':'Clustering includes both outcomes and factors with mean absolute correlation ≥0.40. Tier summaries are unweighted county means: disease prevalence in percent and SVI on a 0–1 scale, not national prevalence estimates. K=4 retains the project’s descriptive four-profile convention despite substantial overlap.',
 '5. Static map: use all clustered counties for fitting, show the contiguous U.S.':'Grey means no matched tier. The cached boundary file uses older county identifiers, so some current counties cannot be drawn. Compound polygon paths preserve islands and interior holes.'}
for j in range(1,len(parts),2):
 title,body=parts[j],parts[j+1].strip()
 if title=='Findings and limits':
  nb.cells.append(nbformat.v4.new_markdown_cell('**Findings and limits**\n\n'+'  \n'.join(line.removeprefix('# ') for line in body.splitlines())))
 else:
  nb.cells.append(nbformat.v4.new_markdown_cell('### '+title+'\n\n'+notes[title]))
  cell=nbformat.v4.new_code_cell(body)
  cell.metadata['sample_section']=title.split('.')[0]
  nb.cells.append(cell)
nb.metadata.update(kernelspec={'name':'python3','display_name':'Python 3 (ipykernel)','language':'python'},
                   language_info={'name':'python'},
                   sample_scope={'blueprint':'../assignment.ipynb','delivery':'Executed notebook; two-page PDF layout deferred',
                                 'github':'https://github.com/Booth-DH/Global_AI_Internship'})
nbformat.validate(nb)
nbformat.write(nb,out/'code_sample.ipynb')
print('Created notebook:',len(nb.cells),'cells;',sum(c.cell_type=='code' for c in nb.cells),'code cells')
print('Code lines:',sum(len(c.source.splitlines()) for c in nb.cells if c.cell_type=='code'))
